---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/volsync.backube/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: slskd
  namespace: download
spec:
  sourcePVC: slskd-config
  trigger:
    schedule: "0 * * * *"
  restic:
    copyMethod: Snapshot
    pruneIntervalDays: 7
    repository: slskd-restic-secret
    cacheCapacity: 1Gi
    cacheStorageClassName: longhorn-cache
    cacheAccessModes: [ReadWriteOnce]
    volumeSnapshotClassName: longhorn-snapclass
    storageClassName: longhorn-snapshot
    accessModes: [ReadWriteOnce]
    moverSecurityContext:
      runAsUser: 1001
      runAsGroup: 1001
      fsGroup: 1001
    retain:
      hourly: 24
      daily: 7
      weekly: 5
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: "slskd-config-dst"
spec:
  trigger:
    manual: restore-once
  restic:
    repository: slskd-restic-secret
    copyMethod: Snapshot # must be Snapshot
    cacheCapacity: 1Gi
    cacheStorageClassName: longhorn-cache
    cacheAccessModes: [ReadWriteOnce]
    volumeSnapshotClassName: longhorn-snapclass
    storageClassName: longhorn-snapshot
    accessModes: [ReadWriteOnce]
    capacity: 2Gi
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.26.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: slskd-restic-secret
  labels:
    app.kubernetes.io/name: slskd
type: Opaque
stringData:
  RESTIC_REPOSITORY: ${SECRET_RESTIC_REPOSITORY_S3}/slskd
  RESTIC_PASSWORD: ${SECRET_RESTIC_PASSWORD_S3}
  AWS_ACCESS_KEY_ID: ${SECRET_MINIO_ACCESS_KEY}
  AWS_SECRET_ACCESS_KEY: ${SECRET_MINIO_SECRET_KEY}
