apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:TlyGZduKPSVei+Y=,iv:wVYHhZAZ1gvpRudjPCDTNKWtrJBtxnVYjbPEt4rRhNQ=,tag:c87P/g9x9NLayrtcOGHasQ==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:xJiXROQK00TBwIgTGiR9qylwnt0=,iv:afTRVU098xQ5/d34m3LBs3/tGtVdFs5d4eEIfMkk8zg=,tag:DKaOK7Pk4YU++tBUn+GZlg==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:LYVIG5kmlASrkhmr64ecLrK6P1haE9d5a7zXG+SkzXl3xnJ2,iv:LhdbzBpWHDqnKDO2bdRPurr6x4zBUpr+ht7nbMtoD2c=,tag:jefINt2rfQ3NJb95skJ7mw==,type:str]
    SECRET_MATRIX_POSTGRESQL_PASSWORD: ENC[AES256_GCM,data:TDpVFd8Z51d7xXU=,iv:VpN3YEwNBQ7SKjU+V6eJxm9TyUt2FgswvRPiWTh1sQU=,tag:6nkp41o7kRpPsD8LEYx2vQ==,type:str]
    SECRET_MATRIX_REDIS_PASSWORD: ENC[AES256_GCM,data:dg6pOz4Knk82roT8WxWn,iv:38Evo1wo7cK3AwmonLW4eAHwoVfWkBzBlZbpKJ2iFgU=,tag:xMV9CemsPQAqkues2iitvA==,type:str]
    SECRET_SYNAPSE_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:iONcpbPsMqVhTnjd09MTb/CSZ7aBq4sqajkw3v7PelACaaf6qCYJpqOvTVJs6kXo7EFKAauynxEuI5/qpBuXXUetLLKP6PCL,iv:JDPsWhhQA6YmLUNUYHrjEOMMTq/CrS+PY5vWXPQzQnA=,tag:uM+CfrRwrm/hFfICKhtowg==,type:str]
    GRAFANA_SYNAPSE_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:7kv/UtF4fE/p2xzOjtAIn8xFqBde5iA7P37sylc80e1GMpUe1WTL3pn4j1uRLOcEruUJk2XN/2I0N++x7s5hng==,iv:WoRgDubqEOHV+4vf4stbFX/xA0fQ8/IJtVf36E0NaL8=,tag:xXL7q7sozDdFgUO+/UVfWQ==,type:str]
    VOLSYNC_RESTIC_PASSWORD: null
    VOLSYNC_MINIO_ACCESS_KEY: ENC[AES256_GCM,data:eYZdMsLPBHCKshj8LYeUrl2P01I=,iv:CXnRztjRCiIcUbtT8c9JnKq6SPCuJO/R1tU66zDVhrk=,tag:sX3fk5k2pI1FkzouguwrQQ==,type:str]
    VOLSYNC_MINIO_SECRET_KEY: ENC[AES256_GCM,data:E8of385vXg/5Auw3KkdUnjKfC1wd/zL3EqLEaIDCTJQ1Gq/0eaBrbA==,iv:Z8ejYXekmIC+QgS2+UcVqhTp6WZLEHlcTYyxd2ecwkM=,tag:r/aEjJ3M+I2YNmyDNuhfzQ==,type:str]
    SECRET_RESTIC_REPOSITORY_S3: ENC[AES256_GCM,data:btUoLvyhXVyOZPgkdajNynb1UzJe5KXXmUbXWGxalulkAV1erUFC4MstXVjdgA==,iv:zorB1GurVbF1MA5nhBwQERnhRE4kaVgPvl2d5W+5SWs=,tag:+Ec4DVGAoOFzejIzCLN80g==,type:str]
    SECRET_RESTIC_PASSWORD_S3: ENC[AES256_GCM,data:2EqmnVVMR4Et3195g7vg,iv:oWIdWNVMvfAY7CKamSqaOJPRmDw2sMEJ4lBQJP4WltM=,tag:f+o4iXNGyFsBjJTQgFC8kg==,type:str]
    SECRET_MINIO_ACCESS_KEY: ENC[AES256_GCM,data:Rq1+HCx1NYPT7TtYYVAuSZ34qH0=,iv:clI+P/4wv81WnqFnp1etfEfK/nTlT5EUprzzpXQ/+h8=,tag:Hrlpik2yxtYE7sSXLkz5WQ==,type:str]
    SECRET_MINIO_SECRET_KEY: ENC[AES256_GCM,data:DTkKqBgDZqQasomufVaeF/elfRXrEX9LbOd/0WHNqDJD1GmY1CQZMQ==,iv:SQYWd7c56qZNQVmQrAgNlqGBRYEaDyAgQ4c40PRrjG0=,tag:maCHwmj3TCHiU86eJ0XYuw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1x9asfknr3janmqkcm9nlcg5hzm59wtdhs6u9lhweaddagnvg9amq22505d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTZjlkNWlkZDZSbzMwZXhG
            S29XTStsa3dKV3Y5NWdjSjhTbHZjdTRTRVhzCktqRlllUUtkK3ZXZGtsK2EzVWs1
            dHVWMDVVaVVUeFRMUFBSazdUNXkrQTAKLS0tIEN2ZTUrOU82NE8rZ2g0TjhyVEp2
            RlBGRDAweWRhMHRGYnFFL0doRzkwbnMK/+R5x6acoA4+iblwJMnj4sE0XpyrdJbs
            dUpzDz6XN0UbH8MXW9Gxwu8hZFFwYQQgwlKt4eqYUMMIJkK/9CoLJg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-29T13:22:52Z"
    mac: ENC[AES256_GCM,data:ohsZMyeHU5/dHsUDLWTpc1H9eDzBeBLxJMZtNDW7w8IF74Llh7lziHejGbYKCmjLcL6sbVkTktAoj4m99NQW8vPCDlfXp7nLOGlhzqo4CV66fbDxF6bbuo/Bjlh26UTuiIyeiiCTdGm9ctqfktGb0ACJ/iaGWwUZgsMkSCWTViQ=,iv:SOWtO6T9VYd4shkt5YF3XoHTR/juu2lu8HG+ZtsLUlM=,tag:DQgUVOSl43T251YrZmYbEA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
