apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./matrix-signing-key.sops.yaml
  - ./internal-ingress.yaml
  - ../../../../templates/volsync
  #- ../../../../templates/gatus/external
