apiVersion: v1
kind: Secret
metadata:
    name: lldap-secret
    namespace: security
stringData:
    LLDAP_JWT_SECRET: ENC[AES256_GCM,data:/vbR/f5oY3/td7sVUk63mjCqMj7aea10n9xzhf13+6O5AvafHj3fd2uNwnyOKskRSANhIWNAd9NavOdxY06A2A==,iv:y3kqA3D8kVSkm6JVFq13r94YeUHktKtV/I3Kpu3m6qU=,tag:nVEczlGFsHCX90H8TkI36g==,type:str]
    LLDAP_LDAP_USER_PASS: ENC[AES256_GCM,data:82QmMqsO9t5gmMZbxD6D,iv:AsEfRCzgCH5qTSNFA0bA3goGY+xNmAYEHC9+mhkNXSc=,tag:jtsE0ngPTgF4fIhs+/Fw0A==,type:str]
    LLDAP_USER_DN: ENC[AES256_GCM,data:i0p1on0VmJ1OIELp53m8py52szbioGz5I+QlsO6o/Izm91QJI3UE6Q==,iv:+BuE7Aa83UUDM9DKD9g9LH1KOv/3EartRqKbezdzHfI=,tag:CRPl0bPoxT5Wp9VlxIijjA==,type:str]
    LLDAP_LDAP_USER_EMAIL: ENC[AES256_GCM,data:IP+PjuE7I0Y5x+Sbngpv+R9cI+U=,iv:AYBREXuyO7W9sEOVyVfs9wz/Jy7zkFD0expnqjS/Xys=,tag:aoE2ht5ZuTmC5igiU4bscg==,type:str]
    LLDAP_SERVER_KEY_SEED: ENC[AES256_GCM,data:ZXU2J9o7dHptrzqCqdwm3YWbn5yYJBhB+U5COEzuqIewRZfMLn2dpyZ936K2ZsJ2c2ZKrikHeNuBme3INoPFZA==,iv:DV5aYeZcaa4WzG92y9rCUKRNJO9TCKYzLEbze9X6qMk=,tag:Dig1jDDYPZeXsGvQXT583w==,type:str]
    LLDAP_DATABASE_URL: ENC[AES256_GCM,data:XG4H5AfQiU9oQFhN+aq3kNzqJ8mTw1+wHJailvRBexd7HENRBi7FcdPVwFua99m9jGiQCT+6t7r+06Tzz36rVAUoK5V8miMcTpndNcqjWw==,iv:lTXcPucBaRPldmEL62iIEgldlWsXrvIJJ02zDjKsbp8=,tag:5KkyVHPtmt4IZXu5fihBcg==,type:str]
    #ENC[AES256_GCM,data:Vb31CDzHxj8k5vVGWy8=,iv:HYvUz6ut9ooNpvLyg+5xSpegffjT+PI5jKG3QljPU3k=,tag:4MQGe0y2s37YyWE4wI1nQQ==,type:comment]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:wo56hEE=,iv:c39cgjE8aqX2YYwc8Qr/tmOPPmP7ctp8+Vh2NzUd/wo=,tag:xihwXsBDXRlSz1B5fq75gQ==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:nxAvanBY6nU/tgrrHeqgtmYI59mkCpKfRzEWoxk8qegbxy+RkzjuWQ==,iv:lZZDVpQwIRdIVyz1/ik3jV+8iKipLoGrRcS4GCnF6WA=,tag:rQ6f9iuviepujaOTI6f8HQ==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:vCNCg2A=,iv:QrB81FQqcE5/al63sJy0Yccu6o+184YFBTunSRYoe2c=,tag:W/JdLxp7IL/A2TXSzgbVuw==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:H3s4IhiyXbDACjhtRgdU,iv:XX94KD10fnTES4Pqtb5BGVuqiQ6sz4JnUALDOBj5DCA=,tag:d2vsggfHJx7bdYrPa5F+fw==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:mKTTJpcwhEB4swsXWF18,iv:+CHqL/X0pSKQtrioCcpW8QYzm6Xn1HEKx9q9+0YS/YA=,tag:U/tB4wiMIqW2Yi9b3WbQYQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1x9asfknr3janmqkcm9nlcg5hzm59wtdhs6u9lhweaddagnvg9amq22505d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiUVAxVGVtYm0xYnlSR0R0
            U3g0NFNLaDZwWEowd2p2YzBMbndBdHZ0a2cwCjVtVlV1eFdYRnJDWFNYWjhMV3Y1
            dWg0dzhJakhaMFFIWlhUbEhoZWRSMncKLS0tIC9CbjZPNlRaVEVRRkswYk5BWFhn
            Mkg2Q05kOWt6Ukd5UmQ1YUI3ZUhKSkkKLNppPBCczkGiLVK+TE16Gd1qkagg8NN5
            w48BsCcvGiglwc9o+E35kHpx8C9aH8FYrFnwujvWgBMISX7Pwsfmpg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-08T11:54:32Z"
    mac: ENC[AES256_GCM,data:HSBAff4xQ9Qi+CkGO4cm2WMo3VKTBcSce8E+UlbW/qBJDGdIYK6J4t14v7sb4E7FUVTeV9HsB/leMsIaESyZxxiiBCmMOdH+er+olg0vzj+hCMy8SuCu2m5ZdEqR2gNgC7jQDvlKvO2TCFbmulAslQc2IkTrSHb8hpykn9vKWvo=,iv:N0czW7M8KHekT7C73RfrntS9qjv69QV4FEwRLmWpIHY=,tag:sonbwTbySds9v5hgHjMUZQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
